movie/movie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movies.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie/movies/urls.py
from django.urls import path
from movies import views
app_name='movies'

urlpatterns = [
    path('',views.home,name='home'),
    path('add/',views.add,name='add'),
    path('add1/',views.add1,name='add1'),
    path('mdetails/<int:p>',views.mdetails,name='mdetails'),
    path('editmoviebyid/<int:p>',views.editmoviebyid,name="editmoviebyid"),
    path('deletemoviebyid/<int:p>',views.deletemoviebyid,name="deletemoviebyid"),


]

movie/movies/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
class Movies(models.Model):
    title=models.CharField(max_length=50)
    director=models.CharField(max_length=20)
    year=models.IntegerField()
    poster=models.ImageField(upload_to="movies/poster",null=True,blank=True)
    def __str__(self):
        return self.title

movie/movies/forms.py
from django import forms
from movies.models import Movies

# form definition

class movieform(forms.ModelForm):
    class Meta:
        model=Movies
        fields='__all__'

movie/movies/views.py
from django.shortcuts import render
from movies.models import Movies
from movies.forms import movieform
# Create your views here.

def home(request):
    m=Movies.objects.all()
    return render(request,'home.html',{'Movies':m})


def add(request):# user defined
    if(request.method=="POST"):
        ti=request.POST['t']
        dire=request.POST['d']
        yr=request.POST['y']
        pos=request.FILES['psr']
        m=Movies.objects.create(title=ti,director=dire,year=yr,poster=pos)
        m.save()
        return home(request)
    return render(request,'add.html')
def add1(request):# build in type
    form=movieform()
    if(request.method=="POST"):
        form=movieform(request.POST,request.FILES)
        if(form.is_valid()):
            form.save()
        return mdetails(request)
    return render(request,'add1.html',{'form':form})



def mdetails(request,p):
    m=Movies.objects.get(id=p)
    return render(request,'mdetails.html',{'Movies':m})


def deletemoviebyid(request,p):
    m=Movies.objects.get(id=p)
    m.delete()
    return home(request)


def editmoviebyid(request,p):
    m=Movies.objects.get(id=p)
    form=movieform(instance=m)
    if(request.method=="POST"):
        form=movieform(request.POST,request.FILES,instance=m)
        if form.is_valid():
            form.save()
            return mdetails(request,p)
    return render(request,'add1.html',{'form':form})

movie/templates/add.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br><br>
<form method="POST" style="color:red;" enctype="multipart/form-data">
  {% csrf_token %}
<i style="font-size:25px;">MOVIE DETAILS</i>
  <br><br>
<div class="mb-3">
  <label  class="form-label" >TITLE </label>
  <input type="text" class="form-control" name="t" placeholder="Enter the Title">
</div>
<div class="mb-3">
  <label  class="form-label" >DIRECTOR</label>
  <input type="text" class="form-control" name="d" placeholder="Enter the Director">
</div>

<div class="mb-3">
  <label class="form-label" >YEAR</label>
  <input type="number" class="form-control" name="y" placeholder="Enter the Year">
</div>

<div class="mb-3">
  <label class="form-label" >POSTER</label>
  <input type="file" class="form-control" name="psr" >
</div>
<div class="mb-3">
  <input type="submit">
</div>
</form>

{% endblock %}

movie/templates/add1.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br><br>

<i style="font-size:25px;color:red;">Add Movie</i>
<br>
<br>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
{{ form.as_table }}
    </table>
    <br>
    <br>
    <input type="submit">

</form>
{% endblock %}

movie/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" style="color:red;margin-left:20px;size:20px;" href="{% url 'movies:home' %}">Anime Movies</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

 <div class="container-fluid" align="right">
    <a class="navbar-brand bg-light" style="color:black" href="{% url 'movies:add' %}">ADD</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>

</nav>
{% block content %}
{% endblock %}

</body>
</html>

movie/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
  <h2 class="text" align="left" style="margin-top:30px;margin-left:180px;font-style:italic;">MOVIES</h2>

    <br><br>
    <div class="row">
  {% for i in Movies %}


      <div class="card bg-dark" style="width: 18rem;margin-left:200px;">
          <br>
          <img src="{{i.poster.url}}" class="card-img-top" alt="...">
            <div class="card-body" style="color:white;">
                <h5 class="card-title">NAME : {{i.title}} </h5>
              <H6 class="card-text"> DIRECTORS NAME : {{i.director}} <br></H6><p class="text-decoration">YEAR :{{i.year}} </p>
                <a  class="btn btn-danger" href="{% url 'movies:mdetails' i.id %}">More</a>
            </div>
      </div>

{% endfor %}
</div>

{% endblock %}

movie/templates/mdetails.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br>
<h1>Movie Details</h1>
<br>

<table class="table table-bordered " style="color:black;" >
    <tr>
        <th>POSTER</th>
        <td><img  src="{{Movies.poster.url}}" width="100px"height="100px" ></td>
    </tr>
    <tr>
        <th>Movie ID</th>
        <td>{{Movies.id}}</td>
    </tr>
    <tr>
        <th>TITLE</th>
        <td>{{Movies.title}}</td>
    </tr>
    <tr>
        <th>DIRECTOR</th>
        <td>{{Movies.director}}</td>
    </tr>
    <tr>
        <th>YEAR</th>
        <td>{{Movies.year}}</td>
    </tr>

    <tr>
        <th>EDIT</th>
        <td><a class="btn btn-success" href="{% url 'movies:editmoviebyid' Movies.id %}">Edit</a></td>
    </tr>
    <tr>
        <th>DELETE</th>
        <td><a class="btn btn-danger" href="{% url 'movies:deletemoviebyid' Movies.id %}">Delete</a></td>
    </tr>





{% endblock %}